### ISSUE TITLE
Any documentation on auto_processing_file, auto_broken, and auto_done files?

### ISSUE THREAD

**Issue by dalelotts** [whmou/insta360-auto-converter#9]
Just forked this and will be contributing some changes back if I can manage to make some useful changes. =) 

Can you give a quick overview of what these files mean / do?

**Comment by whmou** [comment]
Hi @dalelotts ,
sure, I was trying to use the google drive folder as task list,  

**auto_processing_file**: the insv file is under transcoding.
**auto_broken**: the transcoding process somehow went wrong. (in my past experiences, it usually due to broken insv files).
**auto_done**: the transcoding process is done.

example:
{FILENAME}_00.insv
{FILENAME}_10.insv
if any of {FILENAME}.auto_processing_file, {FILENAME}.auto_broken, {FILENAME}.auto_done exists in the same google drive folder, the python process won't do the transcoding for {FILENAME}_00(10).insv.

I also noticed that in some cases, auto_broken files with the same name keep being generated, 
but not able to check this issue for now and don't know how to reproduce it yet.

Thanks!

**Comment by whmou** [comment]
simply put, they are just flag files.

**Comment by dalelotts** [comment]
Thanks for the clear explanation!
